name: Build Custom Reader Image

on:
  push:
    tags:
      - 'custom-**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      -
        name: Build web
        run: cd web && npm install && npm run build
      -
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      -
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.1.1
      -
        name: Build Java
        run: |
          mv ./web/dist ./src/main/resources/web
          rm src/main/java/com/htmake/reader/ReaderUIApplication.kt
          gradle -b cli.gradle assemble --info
          mv ./build/libs/*.jar ./reader.jar
      -
        name: Build Docker image
        run: |
          docker build -f ./.github/workflows/Dockerfile -t reader-custom:latest .
          docker save reader-custom:latest | gzip > reader-custom.tar.gz
          ls -lh reader-custom.tar.gz
      -
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reader-custom-image
          path: reader-custom.tar.gz
          retention-days: 7
